export type CommunityMetric = 'leaderboard' | 'nft' | 'staking' | 'equal'
export type TreasuryGov = 'snapshot' | 'creator' | 'tbd'

export type LaunchConfig = {
  // Step 1 — Empire profile
  creatorHandle: string
  tokenName: string
  tokenTicker: string
  description: string

  // Step 2 — Community rewards
  communityMetric: CommunityMetric
  metricApiUrl: string
  minThreshold: number
  communityPct: number

  // Step 3 — Creator allocation
  creatorPct: number
  creatorWallet: string

  // Step 4 — Treasury
  treasuryGov: TreasuryGov

  // Step 5 — ZAO partnership (fixed defaults, creator acknowledges)
  zaoStakePct: number
  zaoLockMonths: number
}

export const DEFAULT_CONFIG: LaunchConfig = {
  creatorHandle: '',
  tokenName: '',
  tokenTicker: '',
  description: '',
  communityMetric: 'leaderboard',
  metricApiUrl: '',
  minThreshold: 10,
  communityPct: 1,
  creatorPct: 97,
  treasuryGov: 'tbd',
  creatorWallet: '',
  zaoStakePct: 5,
  zaoLockMonths: 12,
}

export function treasuryPct(cfg: LaunchConfig): number {
  return Math.max(0, 100 - cfg.communityPct - cfg.creatorPct)
}

export const METRIC_LABELS: Record<CommunityMetric, string> = {
  leaderboard: 'Leaderboard points',
  nft: 'NFT holding',
  staking: 'Token staking',
  equal: 'Equal share',
}

export const METRIC_DESCRIPTIONS: Record<CommunityMetric, string> = {
  leaderboard: 'Score from an external leaderboard API — best for social creators and Farcaster builders.',
  nft: 'Each NFT = 1 share, weighted by count held — best for PFP and collector communities.',
  staking: 'Token staked × duration = score — best for DAOs and long-term holders.',
  equal: 'Each approved address gets 1/N of the pool — best for small tight-knit groups.',
}

export const GOV_LABELS: Record<TreasuryGov, string> = {
  snapshot: 'Token-weighted Snapshot vote',
  creator: 'Creator decides',
  tbd: 'TBD (set after launch)',
}

export function generateDeployConfig(cfg: LaunchConfig): string {
  const treasury = treasuryPct(cfg)
  const ticker = cfg.tokenTicker.toUpperCase().replace(/^\$/, '')
  const date = new Date().toISOString().slice(0, 10)

  return `# ${cfg.tokenName || '[Token Name]'} — Sparkz Deploy Config

> Generated by the Sparkz Launcher · ${date}
> Creator: @${cfg.creatorHandle || '[handle]'}
> DRAFT — review before deploying on clanker.world

---

## Pre-deploy checklist

- [ ] 0xSplits contract deployed on Base (Step 1 below)
- [ ] Token image ready (1000×1000 PNG)
- [ ] Creator wallet confirmed
- [ ] ZAO stake acknowledged
- [ ] All fields reviewed

---

## Step 1: Deploy the 0xSplits contract

Go to https://app.splits.org (Base network)

| Field | Value |
|-------|-------|
| Network | Base |
| Split type | Split V2 |
| Controller | Creator + ZAO 2-of-2 multisig (recommended) |
| Distribution | Pull (recipients claim as needed) |

Initial placeholder recipients (update to real weights after launch):

| Address | Weight | Label |
|---------|--------|-------|
| ${cfg.creatorWallet || '[CREATOR_WALLET]'} | 50% | Placeholder — creator |
| [ZAO_WALLET] | 50% | Placeholder — ZAO |

> Run \`npm run resolve-wallets && npm run snapshot\` after launch to get real leaderboard weights.

After creating: copy the Split contract address. This goes into the Clanker fee recipient field.

---

## Step 2: Clanker.world deploy config

URL: https://clanker.world/clanker

| Field | Value |
|-------|-------|
| **Token Name** | \`${cfg.tokenName || '[Token Name]'}\` |
| **Symbol** | \`${ticker || '[TICKER]'}\` |
| **Description** | \`${cfg.description || '[Description]'}\` |
| **Chain** | Base |
| **Fee Tier** | 1% |
| **Fee Recipient** | \`[0xSplits contract address from Step 1]\` |
| **Image** | Upload 1000×1000 PNG |

---

## Fee split (${cfg.communityPct}/${cfg.creatorPct}/${treasury})

| Recipient | Share | Mechanism |
|-----------|-------|-----------|
| **Community (${METRIC_LABELS[cfg.communityMetric]})** | **${cfg.communityPct}%** | 0xSplits · weights update ${cfg.communityMetric === 'leaderboard' ? 'weekly from leaderboard API' : cfg.communityMetric === 'nft' ? 'on NFT balance snapshot' : cfg.communityMetric === 'staking' ? 'on staking score' : 'equal share per approved address'} |
| **Creator** | **${cfg.creatorPct}%** | Direct to ${cfg.creatorWallet || '[CREATOR_WALLET]'} |
| **Treasury** | **${treasury}%** | ${GOV_LABELS[cfg.treasuryGov]} |

${cfg.minThreshold > 0 ? `Minimum eligibility threshold: **${cfg.minThreshold} points** (dust prevention)\n` : ''}
---

## ZAO partnership

- ZAO stake: **${cfg.zaoStakePct}% of initial supply**
- Lock: **${cfg.zaoLockMonths} months** with 3-month cliff
- Mechanism: public timelock contract (disclosed at launch)
- ZAO does NOT take a fee slice — ZAO holds the token alongside your community

---

## Post-deploy actions

1. Pin the contract address — update \`NEXT_PUBLIC_TOKEN_ADDRESS\` on Vercel
2. First leaderboard snapshot: \`npm run resolve-wallets && SPLITS_ADDRESS=0x... npm run snapshot\`
3. Update the 0xSplits weights at https://app.splits.org
4. Post the 5-cast Farcaster launch thread
5. Transfer ZAO stake allocation to ZAO's lock contract

---

*One human clicks "Deploy" on clanker.world. Everything else is already done.*
`
}

export function generateXThread(cfg: LaunchConfig): string {
  const ticker = `$${cfg.tokenTicker.toUpperCase().replace(/^\$/, '') || 'TOKEN'}`
  const treasury = treasuryPct(cfg)

  return `# ${cfg.tokenName} X (Twitter) Launch Thread

---

## Tweet 1 — Announcement

@${cfg.creatorHandle || '[creator]'}'s community built the empire before there was a token

[FILL: community size, activity numbers — run \`npm run receipt\` for live snapshot]

they showed up first. without asking what they'd get.

${ticker} is what the empire pays back with — ${cfg.communityPct}% of every trading fee → community → by points

[SITE_URL]

---

## Tweet 2 — Proof

this launch is backed by real numbers, not hype

[FILL: community size, activity numbers — run \`npm run receipt\` for live snapshot]

the boost engine was running before ${ticker} existed.
the leaderboard is live: [SITE_URL/leaderboard]

the people who showed up first already have a fee share waiting.

---

## Tweet 3 — Mechanics

how the 1% trading fee splits:

🟡 ${cfg.communityPct}% → ${METRIC_LABELS[cfg.communityMetric]} (points = share)
🟣 ${cfg.creatorPct}% → @${cfg.creatorHandle || '[creator]'} / operations
⬜ ${treasury}% → treasury (${GOV_LABELS[cfg.treasuryGov]})

the leaderboard split lives in a @0xSplits contract

on-chain. public. updates weekly from the real leaderboard.

verify yourself: [basescan link after deploy]

---

## Tweet 4 — Anthem

@${cfg.creatorHandle || '[creator]'} built this so the people who showed up would have a real stake in what they helped build

they didn't wait for permission

${ticker} is what happens when the empire starts paying back

back the empire ↓

---

## Tweet 5 — "A world opening" / Sparkz frame

${ticker} is a Sparkz launch

Sparkz is building a creator-token launcher where:
→ you set your community's fee split
→ ZAO stakes alongside you (doesn't extract)
→ the launch is one click

this is the first. more are coming.

if you're a creator with a loyal community, stay close

[@bettercallzaal]

---

## Standalone announcement (Discord / community channels)

**${ticker} is live — ${cfg.tokenName}**

The community was already running before the token. No token required to boost, back the empire, or earn a fee share — the engine runs with or without a coin.

${ticker} is the payback mechanism: ${cfg.communityPct}% of every trading fee → community → by ${METRIC_LABELS[cfg.communityMetric]}, weekly, forever.

This is a Sparkz launch — back the community that built the empire, not just the token.

→ Live leaderboard + earnings calculator: [SITE_URL/leaderboard]
→ Token: ${ticker} on Base
→ How it works: [SITE_URL/#tokenomics]

Back the empire. 🟡

---

## Notes

- Fill [SITE_URL] with deployed domain before posting
- Fill leaderboard numbers from \`npm run receipt\` on launch day
- Fill basescan link once token contract is deployed
- Schedule X thread ~30 min after Farcaster thread goes live
- Tag co-builders in Tweet 4 if applicable
- Outbound stays review-gated — review before posting
`
}

export function generateLaunchThread(cfg: LaunchConfig): string {
  const ticker = `$${cfg.tokenTicker.toUpperCase().replace(/^\$/, '') || 'TOKEN'}`
  const treasury = treasuryPct(cfg)

  return `# ${cfg.tokenName} Farcaster Launch Thread

---

## Cast 1 — Announcement

@${cfg.creatorHandle || '[creator]'}'s community built the empire before there was a token

[FILL: community size, activity numbers — run \`npm run receipt\` for live snapshot]

they showed up before any token existed. that's the proof.

${ticker} is what the empire pays back with

→ ${cfg.communityPct}% of every trading fee → community (${METRIC_LABELS[cfg.communityMetric]}) → by points
→ no claiming. it lands in your wallet

you didn't need a token to show up.
now the token shows up for you.

[SITE_URL]

---

## Cast 2 — Proof

this isn't a launch on vibes

it's a launch on receipts

[FILL: community size, activity numbers]

the boost engine was running before ${ticker} existed.
the leaderboard is live: [SITE_URL/leaderboard]

the people who showed up first already have a fee share waiting.

---

## Cast 3 — Mechanics

how ${ticker} fees work:

every trade generates a 1% fee

→ ${cfg.communityPct}% → community (${METRIC_LABELS[cfg.communityMetric]}, weekly refresh)
→ ${cfg.creatorPct}% → @${cfg.creatorHandle || '[creator]'} / operations
→ ${treasury}% → treasury (${GOV_LABELS[cfg.treasuryGov]})

the split lives in a 0xSplits contract — on-chain, public, adjustable

no trust-me-bro. verify on basescan.

---

## Cast 4 — Anthem

you didn't need a token to show up.
but now the token shows up for you.

back the empire. ${ticker}

---

## Cast 5 — "A world opening"

this is a Sparkz launch

no token required to get started — the boost engine, the leaderboard, the community backing —
all of that runs without a coin.

the token is extra. opt-in. the empire pays back with it.

if you're a creator with people who show up for you every day
and you want to give them a real financial stake—

Sparkz is building the launcher.

stay close.

[@bettercallzaal]
`
}
