'use client'

import { useState } from 'react'

const DEFAULT_TIERS = [
  {
    id: 'supporter',
    name: 'Supporter',
    price: 5,
    period: 'month' as const,
    description: 'Back the work. Your name in the weekly receipt.',
    perks: ['Weekly receipt mention', 'Community recognition', 'Leaderboard entry'],
    color: 'slate' as const,
    highlight: false,
  },
  {
    id: 'patron',
    name: 'Patron',
    price: 25,
    period: 'month' as const,
    description: 'Early access to new drops, higher leaderboard weight.',
    perks: [
      'Everything in Supporter',
      '5× leaderboard weight',
      'Early access to new releases',
      'Private Discord/Farcaster channel',
    ],
    color: 'gold' as const,
    highlight: true,
  },
  {
    id: 'council',
    name: 'Council',
    price: 100,
    period: 'month' as const,
    description: 'Top-tier backing. Direct channel to the creator. Max weight.',
    perks: [
      'Everything in Patron',
      '20× leaderboard weight',
      'Direct creator DM access',
      'Quarterly roundtable invite',
      'Council badge on your profile',
    ],
    color: 'violet' as const,
    highlight: false,
  },
]

type TierColor = 'slate' | 'gold' | 'violet'

interface Tier {
  id: string
  name: string
  price: number
  period: 'month' | 'year'
  description: string
  perks: string[]
  color: TierColor
  highlight: boolean
}

const COLOR_MAP: Record<TierColor, { border: string; text: string; badge: string; cta: string }> =
  {
    slate: {
      border: 'border-zao-border',
      text: 'text-slate-300',
      badge: 'bg-slate-800 text-slate-400',
      cta: 'border border-zao-border text-slate-400 hover:border-slate-500',
    },
    gold: {
      border: 'border-gold-500/60',
      text: 'text-gold-400',
      badge: 'bg-gold-500/15 text-gold-400 border border-gold-500/40',
      cta: 'bg-gold-500 text-black hover:bg-gold-400',
    },
    violet: {
      border: 'border-zao-violet/40',
      text: 'text-zao-violet',
      badge: 'bg-zao-violet/15 text-zao-violet border border-zao-violet/40',
      cta: 'border border-zao-violet/50 text-zao-violet hover:bg-zao-violet/10',
    },
  }

function generateTemplate(tiers: Tier[], creatorHandle: string, projectName: string): string {
  const lines = [
    `# Patronage Tiers — ${projectName || creatorHandle || 'Creator'}`,
    '',
    `> Generated by Sparkz · trysparkz.com`,
    `> Creator: @${creatorHandle || 'handle'}`,
    '',
    '---',
    '',
    '## Tiers',
    '',
    ...tiers.map((t) => [
      `### ${t.name} — $${t.price}/${t.period}`,
      '',
      t.description,
      '',
      '**Perks:**',
      ...t.perks.map((p) => `- ${p}`),
      '',
    ]).flat(),
    '---',
    '',
    '## Implementation notes',
    '',
    '- These are tokenless backing tiers — no wallet/gas required from fans',
    '- Activate card payments by setting STRIPE_SECRET_KEY on your Sparkz deployment',
    '- Leaderboard weight multipliers require the Sparkz snapshot script (`npm run snapshot`)',
    '- Community recognition labels sync to the Boostr leaderboard via the weekly snapshot',
    '',
    '## Farcaster / X copy (paste-ready)',
    '',
    tiers.map((t) =>
      `**${t.name} ($${t.price} backing tier):** ${t.description} | ${t.perks.slice(0, 2).join(' · ')}`
    ).join('\n'),
  ]
  return lines.join('\n')
}

export default function PatronageBuilder() {
  const [tiers, setTiers] = useState<Tier[]>(DEFAULT_TIERS)
  const [creatorHandle, setCreatorHandle] = useState('')
  const [projectName, setProjectName] = useState('')
  const [step, setStep] = useState<'build' | 'preview' | 'export'>('build')
  const [editingTier, setEditingTier] = useState<string | null>(null)
  const [newPerk, setNewPerk] = useState<Record<string, string>>({})
  const [copied, setCopied] = useState(false)

  function updateTier(id: string, patch: Partial<Tier>) {
    setTiers((prev) => prev.map((t) => (t.id === id ? { ...t, ...patch } : t)))
  }

  function addPerk(tierId: string) {
    const perk = newPerk[tierId]?.trim()
    if (!perk) return
    setTiers((prev) =>
      prev.map((t) => (t.id === tierId ? { ...t, perks: [...t.perks, perk] } : t))
    )
    setNewPerk((prev) => ({ ...prev, [tierId]: '' }))
  }

  function removePerk(tierId: string, perkIdx: number) {
    setTiers((prev) =>
      prev.map((t) =>
        t.id === tierId ? { ...t, perks: t.perks.filter((_, i) => i !== perkIdx) } : t
      )
    )
  }

  const templateText = generateTemplate(tiers, creatorHandle, projectName)
  const slug = (projectName || creatorHandle || 'creator')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')

  function downloadFile() {
    const blob = new Blob([templateText], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${slug}-patronage-tiers.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  async function copy() {
    await navigator.clipboard.writeText(templateText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="max-w-3xl mx-auto flex flex-col gap-6">
      {/* Step: build */}
      {step === 'build' && (
        <>
          {/* Project info */}
          <div className="bg-zao-card border border-zao-border rounded-2xl p-6 flex flex-col gap-4">
            <h2 className="text-lg font-black text-white">Your details</h2>
            <div className="grid grid-cols-2 gap-3">
              <input
                className="bg-zao-dark border border-zao-border rounded-lg px-3 py-2.5 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-gold-500/60"
                placeholder="@handle (e.g. zaal)"
                value={creatorHandle}
                onChange={(e) => setCreatorHandle(e.target.value.replace(/^@/, ''))}
              />
              <input
                className="bg-zao-dark border border-zao-border rounded-lg px-3 py-2.5 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-gold-500/60"
                placeholder="Project / artist name"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
              />
            </div>
          </div>

          {/* Tier editor */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {tiers.map((tier) => {
              const colors = COLOR_MAP[tier.color]
              const isEditing = editingTier === tier.id

              return (
                <div
                  key={tier.id}
                  className={`rounded-2xl border ${colors.border} bg-zao-card flex flex-col gap-3 p-5`}
                >
                  {tier.highlight && (
                    <div
                      className={`inline-flex self-start items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-semibold ${colors.badge}`}
                    >
                      Featured
                    </div>
                  )}

                  {isEditing ? (
                    <div className="flex flex-col gap-2">
                      <input
                        className="bg-zao-dark border border-zao-border rounded px-2 py-1.5 text-sm text-white focus:outline-none"
                        value={tier.name}
                        onChange={(e) => updateTier(tier.id, { name: e.target.value })}
                      />
                      <div className="flex gap-2 items-center">
                        <span className="text-slate-500 text-sm">$</span>
                        <input
                          type="number"
                          min={1}
                          className="bg-zao-dark border border-zao-border rounded px-2 py-1.5 text-sm text-white w-20 focus:outline-none"
                          value={tier.price}
                          onChange={(e) => updateTier(tier.id, { price: Number(e.target.value) })}
                        />
                        <select
                          className="bg-zao-dark border border-zao-border rounded px-2 py-1.5 text-sm text-slate-300 focus:outline-none"
                          value={tier.period}
                          onChange={(e) =>
                            updateTier(tier.id, { period: e.target.value as 'month' | 'year' })
                          }
                        >
                          <option value="month">/ month</option>
                          <option value="year">/ year</option>
                        </select>
                      </div>
                      <textarea
                        className="bg-zao-dark border border-zao-border rounded px-2 py-1.5 text-sm text-slate-300 resize-none focus:outline-none"
                        rows={2}
                        value={tier.description}
                        onChange={(e) => updateTier(tier.id, { description: e.target.value })}
                      />
                    </div>
                  ) : (
                    <div>
                      <h3 className={`text-base font-black text-white`}>{tier.name}</h3>
                      <div className="flex items-baseline gap-1 mt-0.5">
                        <span className="text-2xl font-black text-white">${tier.price}</span>
                        <span className="text-xs text-slate-500">/{tier.period}</span>
                      </div>
                      <p className="text-xs text-slate-400 mt-1.5 leading-relaxed">
                        {tier.description}
                      </p>
                    </div>
                  )}

                  {/* Perks */}
                  <ul className="flex flex-col gap-1.5">
                    {tier.perks.map((perk, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-xs">
                        <span className={`mt-0.5 shrink-0 ${colors.text}`}>✓</span>
                        <span className="text-slate-300 flex-1">{perk}</span>
                        {isEditing && (
                          <button
                            onClick={() => removePerk(tier.id, idx)}
                            className="text-slate-700 hover:text-red-400 shrink-0"
                          >
                            ✕
                          </button>
                        )}
                      </li>
                    ))}
                  </ul>

                  {/* Add perk when editing */}
                  {isEditing && (
                    <div className="flex gap-2">
                      <input
                        className="flex-1 bg-zao-dark border border-zao-border rounded px-2 py-1.5 text-xs text-slate-300 placeholder:text-slate-700 focus:outline-none"
                        placeholder="Add a perk..."
                        value={newPerk[tier.id] ?? ''}
                        onChange={(e) =>
                          setNewPerk((prev) => ({ ...prev, [tier.id]: e.target.value }))
                        }
                        onKeyDown={(e) => e.key === 'Enter' && addPerk(tier.id)}
                      />
                      <button
                        onClick={() => addPerk(tier.id)}
                        className="text-xs px-2 rounded border border-zao-border text-slate-500 hover:text-gold-400"
                      >
                        +
                      </button>
                    </div>
                  )}

                  <button
                    onClick={() => setEditingTier(isEditing ? null : tier.id)}
                    className="text-xs text-slate-600 hover:text-slate-400 transition-colors mt-auto pt-1 border-t border-zao-border"
                  >
                    {isEditing ? '✓ Done editing' : 'Edit tier'}
                  </button>
                </div>
              )
            })}
          </div>

          <button
            onClick={() => setStep('preview')}
            className="w-full py-3 rounded-xl bg-gold-500 text-black font-bold text-sm hover:bg-gold-400 transition-colors"
          >
            Preview tiers →
          </button>
        </>
      )}

      {/* Step: preview */}
      {step === 'preview' && (
        <>
          <div className="bg-zao-card border border-zao-border rounded-2xl p-6">
            <h2 className="text-lg font-black text-white mb-1">Preview</h2>
            <p className="text-sm text-slate-400 mb-6">
              This is how your tiers will appear to fans — no wallet required to sign up.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {tiers.map((tier) => {
                const colors = COLOR_MAP[tier.color]
                return (
                  <div
                    key={tier.id}
                    className={`rounded-2xl border ${colors.border} bg-zao-dark p-5 flex flex-col gap-3`}
                  >
                    {tier.highlight && (
                      <div
                        className={`inline-flex self-start items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${colors.badge}`}
                      >
                        Most popular
                      </div>
                    )}
                    <div>
                      <h3 className="text-base font-black text-white">{tier.name}</h3>
                      <div className="flex items-baseline gap-1 mt-0.5">
                        <span className="text-2xl font-black text-white">${tier.price}</span>
                        <span className="text-xs text-slate-500">/{tier.period}</span>
                      </div>
                      <p className="text-xs text-slate-400 mt-1.5">{tier.description}</p>
                    </div>
                    <ul className="flex flex-col gap-1.5 text-xs">
                      {tier.perks.map((p, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className={`${colors.text} shrink-0 mt-0.5`}>✓</span>
                          <span className="text-slate-300">{p}</span>
                        </li>
                      ))}
                    </ul>
                    <button
                      className={`mt-auto w-full py-2 rounded-xl text-sm font-bold transition-colors ${colors.cta}`}
                      disabled
                    >
                      Back for ${tier.price}/{tier.period}
                    </button>
                  </div>
                )
              })}
            </div>

            <p className="text-xs text-slate-600 mt-4 text-center">
              Buttons activate when Stripe is configured. Fans pay by card — no wallet needed.
            </p>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => setStep('build')}
              className="px-5 py-2.5 rounded-xl border border-zao-border text-slate-400 text-sm hover:border-slate-500 transition-colors"
            >
              ← Edit
            </button>
            <button
              onClick={() => setStep('export')}
              className="flex-1 py-2.5 rounded-xl bg-gold-500 text-black font-bold text-sm hover:bg-gold-400 transition-colors"
            >
              Export template →
            </button>
          </div>
        </>
      )}

      {/* Step: export */}
      {step === 'export' && (
        <>
          <div className="bg-zao-card border border-zao-border rounded-2xl p-6 flex flex-col gap-4">
            <div className="flex items-center gap-2">
              <span className="text-green-400 text-xl">✓</span>
              <h2 className="text-lg font-black text-white">Patronage template ready.</h2>
            </div>
            <p className="text-sm text-slate-400">
              Download the template to share with your team or drop into your Sparkz deployment.
              The markdown includes paste-ready Farcaster and X copy.
            </p>

            <div className="flex flex-col gap-3">
              <button
                onClick={downloadFile}
                className="w-full py-3 px-5 rounded-lg border border-gold-500 text-gold-400 hover:bg-gold-500/10 font-semibold text-sm transition-colors flex items-center justify-between"
              >
                <span>{slug}-patronage-tiers.md</span>
                <span className="text-xs text-slate-500">Markdown template + launch copy</span>
                <span>↓</span>
              </button>
              <button
                onClick={copy}
                className="w-full py-3 px-5 rounded-lg border border-zao-border text-slate-400 hover:border-slate-500 font-semibold text-sm transition-colors"
              >
                {copied ? '✓ Copied!' : 'Copy to clipboard'}
              </button>
            </div>

            <div className="bg-zao-dark border border-zao-border rounded-xl px-4 py-3 text-xs text-slate-500 space-y-1">
              <p className="font-semibold text-slate-400">To activate card payments</p>
              <p>• Set STRIPE_SECRET_KEY in your Vercel env vars</p>
              <p>• Set up a Stripe product for each tier (price IDs → env vars)</p>
              <p>• The /back page routes fans to Stripe Checkout when keys are present</p>
              <p>• No token needed — fans pay by card, earn leaderboard weight</p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => setStep('preview')}
              className="px-5 py-2.5 rounded-xl border border-zao-border text-slate-400 text-sm hover:border-slate-500 transition-colors"
            >
              ← Back
            </button>
            <button
              onClick={() => {
                setStep('build')
                setCreatorHandle('')
                setProjectName('')
                setTiers(DEFAULT_TIERS)
              }}
              className="flex-1 py-2.5 rounded-xl border border-zao-border text-sm text-slate-400 hover:text-gold-400 hover:border-gold-500/40 transition-colors"
            >
              New template ↩
            </button>
          </div>
        </>
      )}
    </div>
  )
}
