'use client'

import { useState, useCallback } from 'react'
import type { WizardSeedEntry } from '@/lib/examples'

const ROLES = [
  'Artist',
  'Featured Artist',
  'Producer',
  'Co-Producer',
  'Songwriter',
  'Co-Writer',
  'Manager',
  'Label',
  'Publisher',
  'Mixer',
  'Mastering Engineer',
  'Other',
]

interface Collaborator {
  id: string
  name: string
  role: string
  wallet: string
  pct: number
}

function uid() {
  return Math.random().toString(36).slice(2, 9)
}

function CollaboratorRow({
  col,
  onChange,
  onRemove,
  canRemove,
}: {
  col: Collaborator
  onChange: (patch: Partial<Collaborator>) => void
  onRemove: () => void
  canRemove: boolean
}) {
  const inputCls =
    'bg-zao-dark border border-zao-border rounded-lg px-3 py-2 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-gold-500/60 transition-colors'

  return (
    <div className="bg-zao-dark border border-zao-border rounded-xl p-4 flex flex-col gap-3">
      <div className="grid grid-cols-2 gap-3">
        <input
          className={inputCls + ' col-span-2 sm:col-span-1'}
          placeholder="Name or handle (e.g. @zaal)"
          value={col.name}
          onChange={(e) => onChange({ name: e.target.value })}
        />
        <select
          className={inputCls + ' col-span-2 sm:col-span-1 bg-zao-dark'}
          value={col.role}
          onChange={(e) => onChange({ role: e.target.value })}
        >
          {ROLES.map((r) => (
            <option key={r} value={r}>
              {r}
            </option>
          ))}
        </select>
      </div>
      <div className="grid grid-cols-2 gap-3 items-center">
        <input
          className={inputCls + ' font-mono text-xs'}
          placeholder="0x... (Base wallet)"
          value={col.wallet}
          onChange={(e) => onChange({ wallet: e.target.value })}
        />
        <div className="flex items-center gap-2">
          <input
            type="number"
            min={1}
            max={99}
            className={inputCls + ' w-24 text-right'}
            value={col.pct || ''}
            onChange={(e) => onChange({ pct: Math.min(99, Math.max(0, Number(e.target.value))) })}
            placeholder="0"
          />
          <span className="text-slate-400 text-sm">%</span>
          {canRemove && (
            <button
              onClick={onRemove}
              className="ml-auto text-xs text-slate-600 hover:text-red-400 transition-colors"
              title="Remove"
            >
              ✕
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

function SplitBar({ cols }: { cols: Collaborator[] }) {
  const total = cols.reduce((s, c) => s + c.pct, 0)
  const colors = [
    'bg-gold-400',
    'bg-zao-violet',
    'bg-green-500',
    'bg-blue-500',
    'bg-pink-500',
    'bg-orange-500',
    'bg-teal-500',
    'bg-red-500',
  ]

  if (total === 0) return null

  return (
    <div className="rounded-xl overflow-hidden h-4 flex w-full">
      {cols
        .filter((c) => c.pct > 0)
        .map((c, i) => (
          <div
            key={c.id}
            className={`${colors[i % colors.length]} h-full`}
            style={{ width: `${(c.pct / Math.max(total, 100)) * 100}%` }}
            title={`${c.name || c.role}: ${c.pct}%`}
          />
        ))}
      {total < 100 && (
        <div
          className="bg-zao-border h-full"
          style={{ width: `${100 - total}%` }}
          title="Unallocated"
        />
      )}
    </div>
  )
}

function generateSplitSheet(
  cols: Collaborator[],
  projectName: string,
  projectDate: string
): string {
  const total = cols.reduce((s, c) => s + c.pct, 0)
  const lines = [
    `# Split Sheet — ${projectName || 'Untitled Project'}`,
    `**Date:** ${projectDate}`,
    `**Total:** ${total}% allocated${total !== 100 ? ` ⚠️ (${100 - total}% unallocated)` : ' ✓'}`,
    '',
    '---',
    '',
    '## Collaborators',
    '',
    '| Name / Handle | Role | Wallet (Base) | Share |',
    '|---------------|------|---------------|-------|',
    ...cols.map(
      (c) =>
        `| ${c.name || '—'} | ${c.role} | \`${c.wallet || 'TBD'}\` | ${c.pct}% |`
    ),
    '',
    '---',
    '',
    '## 0xSplits config (paste into app.splits.org)',
    '',
    '```json',
    JSON.stringify(
      {
        recipients: cols
          .filter((c) => c.wallet && c.pct > 0)
          .map((c) => ({
            address: c.wallet,
            percentAllocation: c.pct,
          })),
        distributorFeePercent: 0,
        controller: 'set-after-deploy',
      },
      null,
      2
    ),
    '```',
    '',
    '---',
    '',
    '## Notes',
    '',
    '- This split sheet was generated by Sparkz by ZAO (trysparkz.com)',
    '- Attest this document on-chain: upload to IPFS (e.g. via w3up.web3.storage) and save the CID',
    '- The 0xSplits controller should be held by the primary creator or a multi-sig',
    '- Splits can be updated via the controller — update this doc and re-attest when they change',
  ]
  return lines.join('\n')
}

function generateSplitsJson(cols: Collaborator[]): string {
  return JSON.stringify(
    {
      recipients: cols
        .filter((c) => c.wallet && c.pct > 0)
        .map((c) => ({
          address: c.wallet,
          percentAllocation: c.pct,
        })),
      distributorFeePercent: 0,
      controller: 'set-after-deploy',
    },
    null,
    2
  )
}

function seedToCols(entries: WizardSeedEntry[]): Collaborator[] {
  return entries.map((e) => ({ id: uid(), name: e.name, role: e.role, wallet: '', pct: e.pct }))
}

const DEFAULT_COLS: Collaborator[] = [
  { id: uid(), name: '', role: 'Artist', wallet: '', pct: 50 },
  { id: uid(), name: '', role: 'Producer', wallet: '', pct: 50 },
]

export default function SplitWizard({
  templateSeed,
}: {
  templateSeed?: { title: string; entries: WizardSeedEntry[] }
}) {
  const today = new Date().toISOString().split('T')[0]
  const [projectName, setProjectName] = useState(templateSeed?.title ?? '')
  const [projectDate, setProjectDate] = useState(today)
  const [cols, setCols] = useState<Collaborator[]>(
    templateSeed ? seedToCols(templateSeed.entries) : DEFAULT_COLS
  )
  const [step, setStep] = useState<0 | 1 | 2>(0)
  const [copied, setCopied] = useState<'sheet' | 'json' | null>(null)

  const total = cols.reduce((s, c) => s + c.pct, 0)
  const isBalanced = total === 100
  const hasWallets = cols.filter((c) => c.pct > 0).every((c) => Boolean(c.wallet))

  const updateCol = useCallback(
    (id: string, patch: Partial<Collaborator>) => {
      setCols((prev) => prev.map((c) => (c.id === id ? { ...c, ...patch } : c)))
    },
    []
  )

  const removeCol = useCallback((id: string) => {
    setCols((prev) => prev.filter((c) => c.id !== id))
  }, [])

  const addCol = () =>
    setCols((prev) => [
      ...prev,
      { id: uid(), name: '', role: 'Co-Writer', wallet: '', pct: 0 },
    ])

  function downloadFile(content: string, filename: string) {
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  async function copyText(text: string, type: 'sheet' | 'json') {
    await navigator.clipboard.writeText(text)
    setCopied(type)
    setTimeout(() => setCopied(null), 2000)
  }

  const slug = (projectName || 'split').toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
  const sheetText = generateSplitSheet(cols, projectName, projectDate)
  const jsonText = generateSplitsJson(cols)

  return (
    <div className="max-w-2xl mx-auto flex flex-col gap-6">
      {/* Step 0: Add collaborators */}
      {step === 0 && (
        <>
          <div className="bg-zao-card border border-zao-border rounded-2xl p-6 flex flex-col gap-4">
            <h2 className="text-lg font-black text-white">Project details</h2>
            <div className="grid grid-cols-2 gap-3">
              <input
                className="col-span-2 sm:col-span-1 bg-zao-dark border border-zao-border rounded-lg px-3 py-2 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-gold-500/60 transition-colors"
                placeholder="Project / song name"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
              />
              <input
                type="date"
                className="col-span-2 sm:col-span-1 bg-zao-dark border border-zao-border rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-gold-500/60 transition-colors"
                value={projectDate}
                onChange={(e) => setProjectDate(e.target.value)}
              />
            </div>
          </div>

          <div className="bg-zao-card border border-zao-border rounded-2xl p-6 flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-black text-white">Collaborators</h2>
              <span
                className={`text-sm font-bold tabular-nums ${
                  isBalanced ? 'text-green-400' : total > 100 ? 'text-red-400' : 'text-gold-400'
                }`}
              >
                {total}% / 100%
              </span>
            </div>

            <SplitBar cols={cols} />

            <div className="flex flex-col gap-3">
              {cols.map((col) => (
                <CollaboratorRow
                  key={col.id}
                  col={col}
                  onChange={(patch) => updateCol(col.id, patch)}
                  onRemove={() => removeCol(col.id)}
                  canRemove={cols.length > 1}
                />
              ))}
            </div>

            <button
              onClick={addCol}
              className="text-sm text-slate-500 hover:text-gold-400 transition-colors border border-dashed border-zao-border hover:border-gold-500/40 rounded-xl py-2.5 px-4 text-center"
            >
              + Add collaborator
            </button>

            {total > 100 && (
              <p className="text-xs text-red-400">
                Total exceeds 100% by {total - 100}% — reduce some shares before continuing.
              </p>
            )}
            {total < 100 && total > 0 && (
              <p className="text-xs text-gold-400">
                {100 - total}% unallocated. Adjust percentages to reach 100%.
              </p>
            )}
          </div>

          <button
            disabled={!isBalanced || (total as number) === 0}
            onClick={() => setStep(1)}
            className="w-full py-3 rounded-xl bg-gold-500 text-black font-bold text-sm hover:bg-gold-400 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
          >
            Review split sheet →
          </button>
        </>
      )}

      {/* Step 1: Review */}
      {step === 1 && (
        <>
          <div className="bg-zao-card border border-zao-border rounded-2xl p-6 flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-black text-white">Split sheet review</h2>
              <span className="text-xs text-green-400 bg-green-900/30 border border-green-700/40 rounded-full px-2.5 py-0.5">
                ✓ 100% allocated
              </span>
            </div>

            <SplitBar cols={cols} />

            <div className="rounded-xl overflow-hidden border border-zao-border">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-zao-dark text-left">
                    <th className="px-4 py-2.5 text-xs text-slate-500 font-semibold uppercase tracking-wider">
                      Name
                    </th>
                    <th className="px-4 py-2.5 text-xs text-slate-500 font-semibold uppercase tracking-wider">
                      Role
                    </th>
                    <th className="px-4 py-2.5 text-xs text-slate-500 font-semibold uppercase tracking-wider text-right">
                      Share
                    </th>
                    <th className="px-4 py-2.5 text-xs text-slate-500 font-semibold uppercase tracking-wider">
                      Wallet
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {cols.map((c) => (
                    <tr key={c.id} className="border-t border-zao-border">
                      <td className="px-4 py-3 text-slate-200">{c.name || '—'}</td>
                      <td className="px-4 py-3 text-slate-400 text-xs">{c.role}</td>
                      <td className="px-4 py-3 text-right font-bold text-white">{c.pct}%</td>
                      <td className="px-4 py-3 font-mono text-xs text-slate-500">
                        {c.wallet
                          ? c.wallet.slice(0, 6) + '…' + c.wallet.slice(-4)
                          : <span className="text-gold-600">no wallet</span>}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {!hasWallets && (
              <div className="bg-gold-400/10 border border-gold-400/30 rounded-xl px-4 py-3 text-xs text-gold-300">
                Some collaborators are missing wallet addresses. You can still export the sheet —
                fill in wallets before deploying to 0xSplits.
              </div>
            )}

            <div className="bg-zao-dark border border-zao-border rounded-xl px-4 py-3 flex flex-col gap-1 text-xs text-slate-500">
              <p className="font-semibold text-slate-400">Before you deploy to 0xSplits:</p>
              <p>1. Download the split sheet and save it somewhere permanent</p>
              <p>2. Upload to IPFS (e.g. w3up.web3.storage) for on-chain attestation</p>
              <p>3. Note the CID — include it in your 0xSplits controller notes</p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => setStep(0)}
              className="px-5 py-2.5 rounded-xl border border-zao-border text-slate-400 hover:border-slate-500 text-sm transition-colors"
            >
              ← Edit
            </button>
            <button
              onClick={() => setStep(2)}
              className="flex-1 py-2.5 rounded-xl bg-gold-500 text-black font-bold text-sm hover:bg-gold-400 transition-colors"
            >
              Export →
            </button>
          </div>
        </>
      )}

      {/* Step 2: Export */}
      {step === 2 && (
        <>
          <div className="bg-zao-card border border-zao-border rounded-2xl p-6 flex flex-col gap-4">
            <div className="flex items-center gap-2">
              <span className="text-green-400 text-xl">✓</span>
              <h2 className="text-lg font-black text-white">Your split sheet is ready.</h2>
            </div>

            <p className="text-sm text-slate-400">
              Download the markdown split sheet to share with your team. Use the JSON to deploy
              your 0xSplits contract on{' '}
              <a
                href="https://app.splits.org"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gold-400 hover:underline"
              >
                app.splits.org
              </a>
              .
            </p>

            <div className="flex flex-col gap-3">
              <button
                onClick={() => downloadFile(sheetText, `${slug}-split-sheet.md`)}
                className="w-full py-3 px-5 rounded-lg border border-gold-500 text-gold-400 hover:bg-gold-500/10 font-semibold text-sm transition-colors flex items-center justify-between"
              >
                <span>{slug}-split-sheet.md</span>
                <span className="text-xs text-slate-500">Markdown split sheet</span>
                <span>↓</span>
              </button>

              <button
                onClick={() => downloadFile(jsonText, `${slug}-splits.json`)}
                className="w-full py-3 px-5 rounded-lg border border-zao-border text-slate-300 hover:border-slate-500 font-semibold text-sm transition-colors flex items-center justify-between"
              >
                <span>{slug}-splits.json</span>
                <span className="text-xs text-slate-500">0xSplits deploy config</span>
                <span>↓</span>
              </button>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => copyText(sheetText, 'sheet')}
                className="flex-1 py-2 rounded-lg border border-zao-border text-xs text-slate-500 hover:text-slate-400 transition-colors"
              >
                {copied === 'sheet' ? '✓ Copied!' : 'Copy sheet'}
              </button>
              <button
                onClick={() => copyText(jsonText, 'json')}
                className="flex-1 py-2 rounded-lg border border-zao-border text-xs text-slate-500 hover:text-slate-400 transition-colors"
              >
                {copied === 'json' ? '✓ Copied!' : 'Copy JSON'}
              </button>
            </div>

            <div className="bg-zao-dark border border-zao-border rounded-xl px-4 py-3 text-xs text-slate-500 space-y-1">
              <p className="font-semibold text-slate-400">Next steps</p>
              <p>• Upload split-sheet.md to IPFS → note the CID (your attestation)</p>
              <p>
                • Paste the JSON into{' '}
                <a
                  href="https://app.splits.org"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-slate-400 underline"
                >
                  app.splits.org
                </a>{' '}
                to deploy the contract
              </p>
              <p>• Set the 0xSplits contract address as the fee recipient in Clanker</p>
              <p>• Run weekly snapshots via the Sparkz launcher to update weights</p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => setStep(1)}
              className="px-5 py-2.5 rounded-xl border border-zao-border text-slate-400 hover:border-slate-500 text-sm transition-colors"
            >
              ← Back
            </button>
            <button
              onClick={() => {
                setStep(0)
                setCols([
                  { id: uid(), name: '', role: 'Artist', wallet: '', pct: 50 },
                  { id: uid(), name: '', role: 'Producer', wallet: '', pct: 50 },
                ])
                setProjectName('')
                setProjectDate(today)
              }}
              className="flex-1 py-2.5 rounded-xl border border-zao-border text-sm text-slate-400 hover:text-gold-400 hover:border-gold-500/40 transition-colors"
            >
              New split sheet ↩
            </button>
          </div>
        </>
      )}
    </div>
  )
}
